# Generated by Django 6.1 on 2026-08-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='keywords', to='blogs.keyword'),
        ),
    ]
