# Generated by Django 6.1 on 2026-08-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_comment_email_alter_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
