# Generated by Django 6.1 on 2026-09-01 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post', to='blogs.keyword'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('taken_at', models.DateField()),
                ('caption', models.TextField()),
                ('images', models.ImageField(blank=True, height_field='height', upload_to='images/', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogs.post')),
            ],
        ),
    ]
