# Generated by Django 6.1 on 2026-09-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_rename_images_image_image_alter_image_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=0),
        ),
    ]
