# Generated by Django 6.1 on 2026-08-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('keywords', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'post',
                'ordering': ['-date'],
            },
        ),
    ]
